[workspace]
members = ["nu-zenoh", "nuze"]
resolver = "3"

[workspace.package]
authors = ["Mahmoud Mazouz <hello@fuzzypixelz.com>"]
edition = "2024"
homepage = "http://zenoh.io"
license = "EPL-2.0 OR Apache-2.0"
repository = "https://github.com/ZettaScaleLabs/nu-zenoh"
version = "0.4.0"

[workspace.dependencies]
clap = "4.5.42"
ctrlc = "3.4.7"
dirs = "6.0.0"
flume = "0.11.1"
nu-cli = { version = "0.114.0" }
nu-cmd-extra = { version = "0.114.0" }
nu-cmd-lang = { version = "0.114.0" }
nu-command = { version = "0.114.0" }
nu-engine = { version = "0.114.0" }
nu-explore = { version = "0.114.0" }
nu-json = { version = "0.114.0" }
nu-protocol = { version = "0.114.0" }
nu-std = { version = "0.114.0" }
nu-zenoh = { version = "0.4.0", path = "nu-zenoh" }
serde = "1.0.219"
tempfile = "3.20.0"
tracing-subscriber = "0.3.19"
# NOTE(fuzzypixelz): when bumping this, don't forget to also bump `nu_zenoh::signature_ext::ZENOH_VERSION`
zenoh = { version = "1.9.0", features = [
  "internal",
  "plugins",
  "shared-memory",
  "stats",
  "unstable",
] }
zenoh-codec = "1.9.0"
zenoh-protocol = "1.9.0"

[patch.crates-io]
"zenoh" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-buffers" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-codec" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-collections" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-config" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-core" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-crypto" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-keyexpr" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-link" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-link-commons" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-link-quic" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-link-quic_datagram" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-link-tcp" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-link-tls" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-link-udp" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-link-unixsock_stream" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-link-ws" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-macros" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-plugin-trait" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-protocol" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-result" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-runtime" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-shm" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-stats" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-sync" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-task" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-transport" = { git = "https://github.com/eclipse-zenoh/zenoh" }
"zenoh-util" = { git = "https://github.com/eclipse-zenoh/zenoh" }
